system:
  dbDriver: mongo
  host: localhost
  port: 5004
  server: gin
  messageBus: rabbitMq 
  serviceDiscovery: consul
  tokenSecretKey: abc
mongo:
  database: my_db
  port: 27017
  host: mongodb
rabbitMq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
consul:
  host: consul
  port: 8500