system:
  dbDriver: mysql
  dbManager: gorm
  host: localhost
  port: 5002
  server: gin
  initdb: true
  messageBus: rabbitMq 
  serviceDiscovery: consul
  tokenSecretKey: abc
mysql:
  database: my_db
  port: 3306
  host: mysql
  user: root
  password: 1234
rabbitMq:
  host: rabbitmq
  port: 5672
  user: guest
  password: guest
consul:
  host: consul
  port: 8500