system:
  dbDriver: mongo
  host: localhost
  port: 5003
  server: gin
  messageBus: rabbitMq 
  serviceDiscovery: consul
  tokenSecretKey: abc
mongo:
  database: my_db
  port: 27017
  host: localhost
rabbitMq:
  host: localhost
  port: 5672
  user: guest
  password: guest