system:
  fromEmail: walterwhite2334@gmail.com
  fromEmailPassword: fbmfjenhetjanwam
  messageBus: rabbitMq
  emailHost: smtp.gmail.com
  emailPort: 587
rabbitMq:
  host: localhost
  user: guest
  password: guest
  port: 5672
  exchange: eshop
  routingKey: userCreated  
  queue: email.userCreated