system:
  dbDriver: mysql
  dbManager: gorm
  host: host.docker.internal
  port: 5001
  messageBus: rabbitMq
  server: gin
  initdb: true
  tokenSecretKey: abc
  tokenExpirationTime: 600 
  serviceDiscovery: consul
mysql:
  database: my_db
  port: 3306
  host: mysql
  user: root
  password: 1234
rabbitMq:
  host: rabbitmq
  user: guest
  password: guest
  port: 5672
  exchange: eshop
  routingKey: userCreated
consul:
  host: consul
  port: 8500
