host: localhost
port: 8001
server: gin
serviceDiscovery: consul
useServiceDiscovery: true
tokenSecretKey: abc
consul:
  host: localhost
  port: 8500
redis:
  host: localhost
  port: 6379
services:
  - name: basket
    address: http://localhost:5003
    routes:
      - path: /baskets/:userId
        method: GET
        middleware: true
      - path: /baskets/addProduct
        method: POST
        middleware: true
      - path: /baskets/:userId/verify
        method: PUT
        middleware: true        
  - name: order
    address: http://localhost:5004
    routes:
      - path: /orders/:userId
        method: GET
        middleware: true
      - path: /orders/:id/complete
        method: PUT
        middleware: true  
  - name: catalog
    address: http://localhost:5002
    routes:
      - path: /products
        method: GET
        middleware: false
      - path: /products
        method: POST
        middleware: true  
  - name: identity
    address: http://localhost:5001
    routes:
      - path: /auth/register
        method: POST
        middleware: false
      - path: /auth/login
        method: POST
        middleware: false
      - path: /auth/verify
        method: PUT
        middleware: false    